name: vocalearn
description: "VocaLearn - Adaptive Learning Engine untuk Personalisasi Modul Praktik Mahasiswa Vokasi"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.5.1

  # Routing (role-based)
  go_router: ^14.2.0

  # Networking (hubungkan ke backend AI Adaptive Engine nanti)
  dio: ^5.4.3

  # Visualisasi kompetensi (radar chart, bar chart)
  fl_chart: ^0.68.0

  # Video demonstrasi praktik
  video_player: ^2.9.1
  chewie: ^1.8.3

  # Pemutar YouTube embedded di modul
  youtube_player_iframe: ^6.0.2

  # Penyimpanan token/session
  flutter_secure_storage: ^9.2.2

  # File picker (upload materi)
  file_picker: ^8.1.2

  # Penampil PDF modul di dalam aplikasi
  flutter_pdfview: ^1.4.5
  path_provider: ^2.1.4

  # URL launcher (buka link YouTube)
  url_launcher: ^6.3.1

  # UI polish
  google_fonts: ^6.2.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/fiks_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/fiks_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
